# Site settings
# Build settings
baseurl: '/my-expressjs.com'
url: 'https://chrisdel101.github.io'
markdown: kramdown

plugins:
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

exclude: 
  - [uk/CHANGELOG.md]
  - vendor/bundle
  - node_modules/


github: [metadata]
